Creating Matrices

> Create list

In [1]:
# Creating a 2x2 array
arr = [[1, 2], [3, 4]]
print(arr)

[[1, 2], [3, 4]]


> Create numpy array via list

In [2]:
import numpy as np

# Convert to NumPy
np.array(arr)

array([[1, 2],
       [3, 4]])

> Convert numpy array to PyTorch tensor

In [3]:
import torch

# Convert to PyTorch Tensor
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

Create Matrices with Default Values¶

> Create 2x2 numpy array of 1's

In [4]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

> Create 2x2 torch tensor of 1's 

In [5]:
torch.ones((2, 2))

tensor([[1., 1.],
        [1., 1.]])

> Create 2x2 numpy array of random numbers

In [6]:
np.random.rand(2, 2)

array([[0.85431578, 0.12445648],
       [0.594153  , 0.21290234]])

> Create 2x2 PyTorch tensor of random numbers

In [7]:
torch.rand(2, 2)

tensor([[0.2937, 0.3134],
        [0.9113, 0.5081]])

<p style="font-family:ComicSansMS; font-size: 24px;"> Seeds for Reproducibility</p>

> Create seed to enable fixed numbers for random number generation

In [8]:
# Seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

> Repeat random array generation to check

In [9]:
# Seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

> Create a numpy array without seed

In [10]:
# No seed
np.random.rand(2, 2)

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

> Repeat numpy array generation without seed

In [11]:
# No seed
np.random.rand(2, 2)

array([[0.96366276, 0.38344152],
       [0.79172504, 0.52889492]])

> Create a PyTorch tensor with a fixed seed

In [13]:
# Torch Seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

> Repeat creating a PyTorch fixed seed tensor

In [14]:
# Torch Seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

> Creating a PyTorch tensor without seed

In [15]:
# Torch No Seed
torch.rand(2, 2)

tensor([[0.3074, 0.6341],
        [0.4901, 0.8964]])

> Repeat creating a PyTorch tensor without seed

In [16]:
# Torch No Seed
torch.rand(2, 2)

tensor([[0.4556, 0.6323],
        [0.3489, 0.4017]])

> Fix a seed for GPU tensors

In [17]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

<p style="font-family:ComicSansMS; font-size: 24px;"> NumPy to Torch</p>

> Create a numpy array of 1's

In [18]:
# Numpy array
np_array = np.ones((2, 2))

print(np_array)

[[1. 1.]
 [1. 1.]]


> Get the type of class for the numpy array

In [19]:
print(type(np_array))

<class 'numpy.ndarray'>


> Convert numpy array to PyTorch tensor

In [20]:
# Convert to Torch Tensor
torch_tensor = torch.from_numpy(np_array)

print(torch_tensor)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


> Get type of class for PyTorch tensor

In [21]:
print(type(torch_tensor))

<class 'torch.Tensor'>


> Create PyTorch tensor from a different numpy datatype

In [22]:
# Data types matter: intentional error
np_array_new = np.ones((2, 2), dtype=np.int8)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.int8)

> Create PyTorch long tensor

In [23]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.int64)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]])

> Create PyTorch int tensor

In [24]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.int32)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

> Create PyTorch byte tensor

In [25]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.uint8)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.uint8)

> Create PyTorch Double Tensor

In [26]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.float64)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [27]:
# Alternatively you can do this too via np.double


# Data types matter
np_array_new = np.ones((2, 2), dtype=np.double)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

> Create PyTorch Float Tensor

In [28]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.float32)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]])