<p style="font-family:ComicSansMS; font-size: 30px;"> Gradients with PyTorch</p>

<p style="font-family:ComicSansMS; font-size: 24px;"> Tensors with Gradients -- Creating Tensors with Gradients</p>

> Method 1: Create tensor with gradients

In [1]:
import torch

a = torch.ones((2, 2), requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

> Check if tensor requires gradients

In [2]:
a.requires_grad

True

> Method 2: Create tensor with gradients

In [3]:
# Normal way of creating gradients
a = torch.ones((2, 2))

# Requires gradient
a.requires_grad_()

# Check if requires gradient
a.requires_grad

True

> A tensor without gradients just for comparison

In [4]:
# Not a variable
no_gradient = torch.ones(2, 2)

no_gradient.requires_grad

False

> Tensor with gradients addition operation

In [5]:
# Behaves similarly to tensors
b = torch.ones((2, 2), requires_grad=True)
print(a + b)
print(torch.add(a, b))

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)
tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


> Tensor with gradients multiplication operation

In [6]:
print(a * b)
print(torch.mul(a, b))

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)


> Create tensor of size 2x1 filled with 1's that requires gradient

In [7]:
x = torch.ones(2, requires_grad=True)
x

tensor([1., 1.], requires_grad=True)

> Simple linear equation with x tensor created

In [8]:
y = 5 * (x + 1) ** 2
y

tensor([20., 20.], grad_fn=<MulBackward0>)

> Simple equation with y tensor

In [9]:
o = (1/2) * torch.sum(y)
o

tensor(20., grad_fn=<MulBackward0>)

> Calculating first derivative

In [10]:
o.backward()
x.grad

tensor([10., 10.])

> If x requires gradient and you create new objects with it, you get all gradients

In [11]:
print(x.requires_grad)
print(y.requires_grad)
print(o.requires_grad)

True
True
True
